### ISSUE TITLE
[Backend] Adicionar suporte ao Docker no projeto

### ISSUE THREAD

**Issue by BeaMarinhoDev** [BeaMarinhoDev/gerenciador-financas#2]
Aqui está a descrição detalhada para a tarefa de adicionar suporte ao Docker no seu projeto:

---

#### **Descrição**
Adicionar a configuração necessária para que o projeto utilize o Docker, permitindo a execução em containers. Isso inclui a criação de um arquivo `Dockerfile` para a aplicação e um arquivo `docker-compose.yml` para gerenciar os serviços, como o banco de dados MySQL.

#### **Detalhes Técnicos**
1. **Dockerfile**:  
   - Criar um `Dockerfile` para a aplicação Node.js.
   - Configurar o ambiente para instalar dependências, copiar os arquivos do projeto e expor a porta 3000.

2. **Docker Compose**:  
   - Criar um arquivo `docker-compose.yml` para gerenciar os serviços.
   - Configurar um container para a aplicação e outro para o banco de dados MySQL.
   - Configurar volumes para persistência de dados do MySQL.

3. **Banco de Dados**:  
   - Configurar o container do MySQL com as credenciais definidas no arquivo .env.
   - Garantir que o script estrutura.sql seja executado na inicialização do banco de dados.

4. **Atualização do README**:  
   - Adicionar instruções no README.md para executar o projeto com Docker.

#### **Passos para Implementação**
1. Criar o arquivo `Dockerfile` na raiz do projeto:
   ```dockerfile
   # filepath: Dockerfile
   FROM node:16

   # Define o diretório de trabalho
   WORKDIR /usr/src/app

   # Copia os arquivos do projeto
   COPY package*.json ./
   RUN npm install

   COPY . .

   # Expõe a porta 3000
   EXPOSE 3000

   # Comando para iniciar a aplicação
   CMD ["npm", "start"]
   ```

2. Criar o arquivo `docker-compose.yml` na raiz do projeto:
   ```yaml
   # filepath: docker-compose.yml
   version: '3.8'

   services:
     app:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "3000:3000"
       environment:
         - DB_HOST=db
         - DB_PORT=3306
         - DB_USER=${DB_USER}
         - DB_PASSWORD=${DB_PASSWORD}
         - DB_NAME=${DB_NAME}
         - JWT_SECRET=${JWT_SECRET}
         - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
       depends_on:
         - db

     db:
       image: mysql:8.0
       container_name: mysql_container
       restart: always
       environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
         MYSQL_DATABASE: ${DB_NAME}
         MYSQL_USER: ${DB_USER}
         MYSQL_PASSWORD: ${DB_PASSWORD}
       ports:
         - "3306:3306"
       volumes:
         - db_data:/var/lib/mysql
         - ./helpers/estrutura.sql:/docker-entrypoint-initdb.d/estrutura.sql

   volumes:
     db_data:
   ```

3. Atualizar o arquivo .env para incluir as variáveis necessárias:
   ```properties
   # Configurações do banco de dados
   DB_HOST=db
   DB_PORT=3306
   DB_USER=root
   DB_PASSWORD=root
   DB_NAME=gerenciador_financas

   # Secrets para JWT
   JWT_SECRET=x34sdjsdsDSsdd
   JWT_EXPIRES_IN=1h
   ```

4. Atualizar o README.md com as instruções para usar o Docker:
   ```markdown
   ## Executando com Docker

   1. Certifique-se de ter o Docker e o Docker Compose instalados.
   2. Construa e inicie os containers:
      ```bash
      docker-compose up --build
      ```
   3. Acesse a aplicação em [http://localhost:3000](http://localhost:3000).
   4. Acesse o Swagger UI em [http://localhost:3000/api-docs](http://localhost:3000/api-docs).
   ```

#### **Critérios de Aceitação**
- O projeto deve ser executado corretamente em containers Docker.
- O banco de dados MySQL deve ser inicializado com o script `helpers/estrutura.sql`.
- As instruções no `README.md` devem ser claras e funcionais.

---

Você pode usar essa descrição para criar a tarefa no GitHub.#### **Critérios de Aceitação**
- O projeto deve ser executado corretamente em containers Docker.
- O banco de dados MySQL deve ser inicializado com o script `helpers/estrutura.sql`.
- As instruções no `README.md` devem ser claras e funcionais.

---

Você pode usar essa descrição para criar a tarefa no GitHub.
